# .scrutinizer.yml - see https://scrutinizer-ci.com/docs/guides/php/continuous-integration-deployment for doc
# Excludes go for things do not contain code, are not managed well by Scrutinizer or are external libraries that
# Chamilo includes but that we cannot update without patching upstream.
build:
    environment:
        mysql: 5.5
        php:
            version: 5.6.0
            ini:
                'date.timezone': 'US/Pacific'
                'phar.readonly': false
        hosts:
            my.chamilodev.net: '127.0.0.1'
    dependencies:
        override:
            - true
        before:
            - php -d memory_limit=2G /usr/bin/composer.phar -v update
filter:
    excluded_paths:
        - tests/*
        - main/img/*
        - main/lang/*
        - app/cache/*
        - app/logs/*
        - web/*
        - vendor/*
        - main/admin/db.php
        - app/Migrations/*
        - main/inc/lib/browser/*
        - main/inc/lib/elfinder/*
        - main/inc/lib/freemindflashbrowser/*
        - main/inc/lib/kses-0.2.2/*
        - main/inc/lib/mimetex/*
        - main/inc/lib/nanogong/*
        - main/inc/lib/pclzip/*
        - main/inc/lib/pear/*
        - main/inc/lib/phpmailer/*
        - main/inc/lib/phpseclib/*
        - main/inc/lib/svg-edit/*
        - main/inc/lib/swfobject/*
        - main/inc/lib/wami-recorder/*
        - main/inc/lib/xajax/*
        - main/auth/cas/lib/CAS/*
checks:
    php:
        code_rating: true
        duplication: true
