imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }
    - { resource: services.yml }

#    - { resource: @ChamiloCoreBundle/Resources/config/admin.yml }
#    - { resource: @ChamiloNotebookBundle/Resources/config/admin.yml }

    # Mopa Bootstrap
    - { resource: mopa/mopa_bootstrap.yml }

    # FriendOfSymfony Bundles
    #- { resource: fos/fos_comment.yml }
#    - { resource: fos/fos_rest.yml }
    - { resource: fos/fos_user.yml }
    #- { resource: fos/fos_elastica.yml }
#    - { resource: fos/fos_message.yml }

  # Sonata Core Bundles
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_cache.yml }
    - { resource: sonata/sonata_seo.yml }
#    - { resource: sonata/sonata_timeline.yml }
    - { resource: sonata/sonata_intl.yml }
    - { resource: sonata/sonata_core.yml }
    - { resource: sonata/sonata_user.yml }

  # Sonata Feature Bundles
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_page.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_translation.yml }
#    - { resource: sonata/sonata_news.yml }
#    - { resource: sonata/sonata_user.yml }
#    - { resource: sonata/sonata_notification.yml }
    - { resource: sonata/sonata_classification.yml }
    - { resource: sonata/sonata_timeline.yml }

#    - { resource: @CmfBlogBundle/Resources/config/cmf_routing_auto.xml }
#    - { resource: @CmfBlogBundle/Resources/config/admin.yml }

    - { resource: ivory_ckeditor.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
        name: ch_sid

    fragments:       ~
    http_method_override: true

theodo_evolution_session:
    bag_manager_service: theodo_evolution.session.symfony1.bag_manager
    bag_configuration_service: theodo_evolution.session.symfony1.bag_manager_configuration

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    base_template_class: Sonata\CacheBundle\Twig\TwigTemplate14

    form:
        resources:
            - 'bootstrap_3_horizontal_layout.html.twig'
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            - 'SonataMediaBundle:Form:media_widgets.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'

    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

#    paths:
#          "%kernel.root_dir%/../src/Chamilo/CoreBundle/Resources/views/default": template_style

    globals:
          show_toolbar: true
          show_footer: true
          software_name: Chamilo
          version: 2
          session_teachers:
          teachers:
          news_counter:
          news_list:
          messages_count:
          message_link:
          is_profile_editable:
          plugin_footer_left:
          plugin_footer_center:
          plugin_content_bottom:
          plugin_header_left:
          plugin_header_center:
          plugin_header_right:
          plugin_header_main:
          plugin_menu_bottom:
          plugin_menu_top:
          plugin_content_top:
          plugin_footer_right:
          footer_extra_content:
          course_session_block:
          show_course_shortcut:
          show_course_navigation_menu:
          actions:
          header:
          message:
          show_media_element: 1

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                # if using pdo_sqlite as your database driver:
                #   1. add the path in parameters.yml
                #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
                #   2. Uncomment database_path in parameters.yml.dist
                #   3. Uncomment next line:
                #     path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        # auto_mapping: true
        entity_managers:
            default:
                auto_mapping: true
                mappings: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

doctrine_migrations:
    dir_name: %kernel.root_dir%/../app/Migrations/Schema/V111
    namespace: Application\Migrations\Schema\V111
    table_name: version
    name: Chamilo Migrations

# Grid default template
#apy_data_grid:
#    theme: ChamiloCoreBundle::grid.html.twig
#
stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true
    orm:
        default:
            tree: true
            timestampable: true
            sluggable: true
            sortable: true

#liip_theme:
#    themes: ['web', 'tablet', 'phone']
#    active_theme: 'web'
#    assetic_integration: true

#oneup_flysystem:
#    adapters:
#        local.adapter:
#            local:
#                directory: %kernel.root_dir%/courses
##        s3.adapter:
##              awss3v3:
##                  client: s3_client # add service "s3_client"
##                  bucket: ~
##                  prefix: ~
#
#    filesystems:
#        course:
#            adapter: local.adapter
#            cache: ~
#            alias: ~
#            mount: ~

#jms_translation:
#    configs:
#        app:
#            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
#            output_dir: %kernel.root_dir%/Resources/translations
#            ignored_domains: [routes]
#            excluded_names: ["*TestCase.php", "*Test.php"]
#            excluded_dirs: [cache, data, logs]
##            extractors: [alias_of_the_extractor]

fm_elfinder:
    assets_path: /chamilo_master/web/assets
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
#                    uploads:
#                        show_hidden: false # defaults to false
#                        driver: LocalFileSystem
#                        path: uploads
#                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
#                        upload_deny: ['all']
#                        upload_max_size: 2M
                    local:
                        driver: Flysystem
                        path: uploads
                        flysystem:
                            type: local
                            options:
                              local:
                                  path: %kernel.root_dir%/../web/media/
                        upload_allow: ['all']
                        #upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        #upload_deny: ['all']
                        upload_max_size: 2M

#lunetics_locale:
#    guessing_order:
#        - query
#        - router
#        - session
#        #- browser
#    allowed_locales: "%locales%"

knp_menu:
    twig: true
#
#hwi_oauth:
#    firewall_names: [main]
#    resource_owners:
#        any_name:
#            type:                github
#            client_id:           <client_id>
#            client_secret:       <client_secret>

#gregwar_captcha:

# Doctrine audit
sonata_doctrine_orm_admin:
    audit:
        force: false # Audits are set in the admin.yml files with audit:true
