# if you change the class configuration, please also alter the fos_user.yml file
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    FOSUserBundle: ~
                    ChamiloUserBundle: ~
                    SonataUserBundle: ~
sonata_user:
    admin:
        user:
            class: Chamilo\UserBundle\Admin\UserAdmin
        group:
            class: Chamilo\UserBundle\Admin\GroupAdmin

    class:
        # Entity Classes
        user: Chamilo\UserBundle\Entity\User
        group: Chamilo\UserBundle\Entity\Group

    security_acl:             false
    table:
        user_group:           fos_user_user_group

    impersonating:
        route:                page_slug
        parameters:           { path: / }

#    google_authenticator:
#        server:               %sonata_user.google_authenticator.server%
#        enabled:              true

    manager_type:             orm

    profile:
        dashboard:
            blocks:
                - { position: left, type: sonata.block.service.text, settings: { content: "<h2>Welcome!</h2> <p>This is a sample user profile dashboard, feel free to override it in the configuration! Want to make this text dynamic? For instance display the user's name? Create a dedicated block and edit the configuration!</p>"} }
                #- { position: left, type: sonata.order.block.recent_orders, settings: { title: Recent Orders, number: 5, mode: public }}
#                - { position: right, type: sonata.timeline.block.timeline, settings: { max_per_page: 15 }}
#                - { position: right, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 5, mode: public }}
#                - { position: right, type: sonata.news.block.recent_comments, settings: { title: Recent Comments, number: 5, mode: public }}
        menu:
            - { route: 'sonata_user_profile_show', label: 'sonata_profile_title', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
            #- { route: 'sonata_customer_addresses', label: 'link_list_addresses', domain: 'SonataCustomerBundle'}
            #- { route: 'sonata_order_index', label: 'order_list', domain: 'SonataOrderBundle'}
        form:
            type:                 sonata_user_registration
            handler:              sonata.user.profile.form.handler.default
            name:                 sonata_user_registration_form
            validation_groups:
                - Profile

#        register:
#            form:
#                type:                 chamilo_sonata_user_registration
#                handler:              sonata.user.registration.form.handler.default
#                name:                 chamilo_sonata_user_registration
#                validation_groups:
#                  - Registration
#                  - Default
