<?php

namespace DoctrineProxies\__CG__\Chamilo\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ExtraField extends \Chamilo\CoreBundle\Entity\ExtraField implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'extraFieldType', 'fieldType', 'variable', 'displayText', 'defaultValue', 'fieldOrder', 'visibleToSelf', 'visibleToOthers', 'changeable', 'filter', 'options', 'createdAt', 'type', 'name', 'configuration', 'updatedAt', 'translations', 'currentLocale', 'currentTranslation', 'fallbackLocale');
        }

        return array('__isInitialized__', 'id', 'extraFieldType', 'fieldType', 'variable', 'displayText', 'defaultValue', 'fieldOrder', 'visibleToSelf', 'visibleToOthers', 'changeable', 'filter', 'options', 'createdAt', 'type', 'name', 'configuration', 'updatedAt', 'translations', 'currentLocale', 'currentTranslation', 'fallbackLocale');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ExtraField $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraFieldType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraFieldType', array());

        return parent::getExtraFieldType();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtraFieldType($extraFieldType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtraFieldType', array($extraFieldType));

        return parent::setExtraFieldType($extraFieldType);
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldType', array());

        return parent::getFieldType();
    }

    /**
     * {@inheritDoc}
     */
    public function setFieldType($fieldType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFieldType', array($fieldType));

        return parent::setFieldType($fieldType);
    }

    /**
     * {@inheritDoc}
     */
    public function getVariable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVariable', array());

        return parent::getVariable();
    }

    /**
     * {@inheritDoc}
     */
    public function setVariable($variable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVariable', array($variable));

        return parent::setVariable($variable);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayText($translated = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayText', array($translated));

        return parent::getDisplayText($translated);
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayText($displayText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayText', array($displayText));

        return parent::setDisplayText($displayText);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultValue', array());

        return parent::getDefaultValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultValue($defaultValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultValue', array($defaultValue));

        return parent::setDefaultValue($defaultValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldOrder', array());

        return parent::getFieldOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setFieldOrder($fieldOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFieldOrder', array($fieldOrder));

        return parent::setFieldOrder($fieldOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function isChangeable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isChangeable', array());

        return parent::isChangeable();
    }

    /**
     * {@inheritDoc}
     */
    public function setChangeable($changeable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChangeable', array($changeable));

        return parent::setChangeable($changeable);
    }

    /**
     * {@inheritDoc}
     */
    public function isFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFilter', array());

        return parent::isFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilter($filter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilter', array($filter));

        return parent::setFilter($filter);
    }

    /**
     * {@inheritDoc}
     */
    public function isVisibleToSelf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVisibleToSelf', array());

        return parent::isVisibleToSelf();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisibleToSelf($visibleToSelf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisibleToSelf', array($visibleToSelf));

        return parent::setVisibleToSelf($visibleToSelf);
    }

    /**
     * {@inheritDoc}
     */
    public function isVisibleToOthers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVisibleToOthers', array());

        return parent::isVisibleToOthers();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisibleToOthers($visibleToOthers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisibleToOthers', array($visibleToOthers));

        return parent::setVisibleToOthers($visibleToOthers);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeToString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeToString', array());

        return parent::getTypeToString();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresentation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresentation', array());

        return parent::getPresentation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresentation($presentation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresentation', array($presentation));

        return parent::setPresentation($presentation);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfiguration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfiguration', array());

        return parent::getConfiguration();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfiguration(array $configuration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfiguration', array($configuration));

        return parent::setConfiguration($configuration);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTranslations', array());

        return parent::getTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function addTranslation(\Sylius\Component\Translation\Model\TranslationInterface $translation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTranslation', array($translation));

        return parent::addTranslation($translation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTranslation(\Sylius\Component\Translation\Model\TranslationInterface $translation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTranslation', array($translation));

        return parent::removeTranslation($translation);
    }

    /**
     * {@inheritDoc}
     */
    public function hasTranslation(\Sylius\Component\Translation\Model\TranslationInterface $translation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasTranslation', array($translation));

        return parent::hasTranslation($translation);
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentLocale($currentLocale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentLocale', array($currentLocale));

        return parent::setCurrentLocale($currentLocale);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentLocale', array());

        return parent::getCurrentLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentTranslation(\Sylius\Component\Translation\Model\TranslationInterface $currentTranslation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentTranslation', array($currentTranslation));

        return parent::setCurrentTranslation($currentTranslation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentTranslation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentTranslation', array());

        return parent::getCurrentTranslation();
    }

    /**
     * {@inheritDoc}
     */
    public function setFallbackLocale($fallbackLocale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFallbackLocale', array($fallbackLocale));

        return parent::setFallbackLocale($fallbackLocale);
    }

    /**
     * {@inheritDoc}
     */
    public function getFallbackLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFallbackLocale', array());

        return parent::getFallbackLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function translate($locale = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'translate', array($locale));

        return parent::translate($locale);
    }

}
