parameters:
    faq.entity.question.class: Chamilo\FaqBundle\Entity\Question
    faq.entity.category.class: Chamilo\FaqBundle\Entity\Category
    faq.entity.question_repository.class: Chamilo\FaqBundle\Entity\QuestionRepository
    faq.entity.category_repository.class: Chamilo\FaqBundle\Entity\CategoryRepository

services:
    faq.entity.question_repository:
        factory_service: doctrine
        factory_method: getRepository
        class: '%faq.entity.question_repository.class%'
        arguments: ['%faq.entity.question.class%']

    faq.entity.category_repository:
        factory_service: doctrine
        factory_method: getRepository
        class: '%faq.entity.category_repository.class%'
        arguments: ['%faq.entity.category.class%']